/**
 * The Machine - AI Intervention Suggestions API
 * 
 * POST /api/ai/suggest - Generate intervention options using AI
 */

import { NextRequest, NextResponse } from 'next/server';
import { generateInterventions } from '@/lib/ai';
import type { ThreatIdentification } from '@/lib/assessment';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { identification } = body;

    if (!identification) {
      return NextResponse.json(
        { success: false, error: 'Missing identification data' },
        { status: 400 }
      );
    }

    // Get operator ID from middleware
    const operatorId = request.headers.get('x-operator-id') || 'unknown';

    // Generate suggestions using AI
    const suggestions = await generateInterventions(identification as ThreatIdentification);

    // Log the AI usage
    console.log(`AI suggestions generated by ${operatorId}:`, {
      harmType: identification.harmType,
      suggestionsCount: suggestions.length,
    });

    return NextResponse.json({
      success: true,
      data: suggestions,
    });
  } catch (error) {
    console.error('AI suggestion error:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Failed to generate suggestions with AI',
        message: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
